version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - "37017:27017"
  client:
    build:
      dockerfile: Dockerfile
      context: ./packages/client
    ports:
      - '3000:80'
  server:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
      context: ./packages/server
    ports:
      - '8080:8080'
    links:
      - mongo