version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 37017:27017
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./packages/client:/app
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/server
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./packages/server:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/veaos
    depends_on:
      - mongo
    links:
      - mongo